In [1]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [1]:
# Import datasets
dataset = pd.read_csv('../datasets/50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

NameError: name 'pd' is not defined

In [7]:
# Encode categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
# Split Data in test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Train model
from sklearn.linear_model import LinearRegression

mlr = LinearRegression()

mlr.fit(X_train, y_train)

LinearRegression()

In [10]:
# Test the model
y_pred  = mlr.predict(X_test)

In [11]:
y_pred

array([103015.20159794, 132582.27760817, 132447.73845174,  71976.09851258,
       178537.48221058, 116161.24230168,  67851.69209676,  98791.73374684,
       113969.43533015, 167921.06569553])

In [12]:
acc = mlr.score(X_test, y_test)

In [13]:
acc

0.9347068473282567

In [14]:
np.set_printoptions(precision=2)

In [15]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [16]:
# Predict single value
print(mlr.predict([[1, 0, 0, 160000, 130000, 300000]]))

[181566.92]


In [17]:
# regression codfficient and intercept
print(mlr.coef_)
print(mlr.intercept_)

[ 8.66e+01 -8.73e+02  7.86e+02  7.73e-01  3.29e-02  3.66e-02]
42467.52924852117
